/**
 * Make local development deliver to real inboxes, through your own mailbox.
 *
 *   pnpm mail:relay          write the config and restart Mailpit
 *   pnpm mail:relay --off    stop relaying; Mailpit goes back to catching everything
 *
 * WHY THIS EXISTS
 *
 * Cloudflare Workers cannot open an SMTP socket, so the application can only
 * ever speak HTTP to a mail provider. Every HTTP provider worth using wants a
 * verified sending domain before it will deliver to an address you do not own —
 * Resend, for instance, refuses every recipient except the account owner until
 * a domain is verified. That is correct of them and useless when you want to
 * put a real verification link in front of a handful of real people today.
 *
 * Mailpit is already running locally and it CAN speak SMTP. So it plays the
 * part the Worker cannot: the app posts to Mailpit's HTTP API exactly as it
 * always has, and Mailpit relays the message onward through an ordinary
 * mailbox — a Gmail account with an app password, or any other SMTP server.
 *
 * Verified rather than assumed: a message injected over Mailpit's HTTP API is
 * relayed, not just ones received over SMTP.
 *
 * WHAT IT DOES NOT DO
 *
 * This is a DEVELOPMENT arrangement and cannot be deployed. Production has no
 * Mailpit, so it needs a provider with a verified domain. See docs/ENVIRONMENT.md.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { optional, repoRoot } from "./_env";

/**
 * Recipients that must NEVER be relayed.
 *
 * RFC 2606 and RFC 6761 reserve these, so no mailbox behind one can exist. The
 * E2E suite creates dozens of `@example.test` accounts per run; relaying those
 * would bounce every one of them off a real mail server and, on a personal
 * Gmail account, is a fast route to a sending restriction.
 */
const BLOCKED_RECIPIENTS =
  "(?i)(@([^@]+\\.)?(test|example|invalid|localhost)|@example\\.(com|net|org))$";

const RELAY_DIR = path.join(repoRoot, ".mailpit");
const RELAY_FILE = path.join(RELAY_DIR, "relay.yaml");
const OVERRIDE_FILE = path.join(repoRoot, "compose.override.yaml");

function compose(...args: string[]): void {
  execFileSync("docker", ["compose", ...args], { cwd: repoRoot, stdio: "inherit" });
}

function off(): void {
  fs.rmSync(RELAY_FILE, { force: true });
  fs.rmSync(OVERRIDE_FILE, { force: true });
  console.log("\n  Relay removed. Restarting Mailpit…\n");
  compose("up", "-d", "--force-recreate", "mailpit");
  console.log("\n  Mailpit is catching mail again. Nothing leaves this machine.\n");
}

function main(): void {
  if (process.argv.includes("--off")) return off();

  const host = optional("SMTP_RELAY_HOST", "smtp.gmail.com");
  const port = optional("SMTP_RELAY_PORT", "587");
  const username = optional("SMTP_RELAY_USERNAME", "");
  const password = optional("SMTP_RELAY_PASSWORD", "");

  if (!username || !password) {
    console.error(`
  Missing SMTP_RELAY_USERNAME or SMTP_RELAY_PASSWORD in .env

  For a Gmail account:

    1. Google needs 2-Step Verification switched on for the account.
         https://myaccount.google.com/signinoptions/twosv

    2. Create an APP PASSWORD — a 16-character password that only this tool
       can use, and that you can revoke on its own without touching your
       account password.
         https://myaccount.google.com/apppasswords

    3. Put both in .env (which is gitignored):

         SMTP_RELAY_USERNAME=you@gmail.com
         SMTP_RELAY_PASSWORD=abcdefghijklmnop

    4. Run this again.

  Any other SMTP server works too — set SMTP_RELAY_HOST and SMTP_RELAY_PORT.
`);
    process.exit(1);
  }

  /*
   * `override-from` is not optional with Gmail.
   *
   * Gmail refuses to send a message whose From is not the authenticated
   * account (or one of its verified aliases). Without this the relay
   * authenticates fine and then every message is rejected.
   */
  fs.mkdirSync(RELAY_DIR, { recursive: true });
  fs.writeFileSync(
    RELAY_FILE,
    [
      "# Generated by `pnpm mail:relay`. Gitignored: it holds a password.",
      `host: ${host}`,
      `port: ${port}`,
      "tls: false",
      "starttls: true",
      "auth: plain",
      `username: ${username}`,
      `password: ${password}`,
      `override-from: ${username}`,
      `return-path: ${username}`,
      `blocked-recipients: '${BLOCKED_RECIPIENTS}'`,
      "",
    ].join("\n"),
    { mode: 0o600 },
  );

  fs.writeFileSync(
    OVERRIDE_FILE,
    [
      "# Generated by `pnpm mail:relay`. Gitignored.",
      "#",
      "# Docker Compose merges this over compose.yaml automatically, so the",
      "# committed file stays free of anything machine-specific.",
      "services:",
      "  mailpit:",
      "    volumes:",
      "      - ./.mailpit:/etc/mailpit:ro",
      "    command:",
      "      - --smtp-relay-config=/etc/mailpit/relay.yaml",
      "      # Relay everything EXCEPT the blocked recipients in that file.",
      "      - --smtp-relay-all",
      "",
    ].join("\n"),
  );

  console.log(`
  Relay configured.

    via       ${host}:${port}
    as        ${username}
    from      ${username}   (Gmail rewrites From to the authenticated account)
    never     addresses on reserved test domains — the E2E suite stays local

  Restarting Mailpit…
`);
  compose("up", "-d", "--force-recreate", "mailpit");

  console.log(`
  Done. Set EMAIL_TRANSPORT=mailpit in .env and apps/web/.dev.vars, then:

      pnpm email:test --to someone@gmail.com

  Mail now leaves this machine. It is still copied into http://localhost:8025,
  so you can read exactly what was sent.

  This is a DEVELOPMENT arrangement — Workers cannot speak SMTP, so a deployed
  Inkloom needs a provider with a verified domain instead.
`);
}

main();
